platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: GoDemo

outputs:
- name: coverage-results

run:
  path: ./GoDemo/ci/Scripts/unit-tests.sh
